### ISSUE TITLE
Rename vue-ui to ui and packages

### ISSUE THREAD

**Issue by yangwao** [vue-polkadot/ui#10]
It's pointless to have 3 times Vue in naming, i.e https://github.com/vue-polkadot/vue-ui/tree/vue-identicon

After closing M1 we would like to rename to 
@vue-polkadot/identicon
@vue-polkadot/keyring
@vue-polkadot/settings

Also, this repository should be renamed to https://github.com/vue-polkadot/ui/

According to this fix documentation and broken link in docs

**Comment by vikiival** [comment]
@yangwao ? 🤔

**Comment by yangwao** [comment]
Sure, want to proceed? I would like join it with renaming vue-polkadot to
KodaDot 😁🤘

**Comment by vikiival** [comment]
moved to https://github.com/kodadot/packages

renamed:
vue-api -> dot-api

⚰️  dead:
vue-identicon
vue-keyring

without change:
vue-settings

They will be also unpublished from the `npmjs` in couple of weeks
